

services:
  test-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testhub-dev
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    environment:
      - HMI_ENVIRONMENT=development
    restart: always
